### PR TITLE
Bug squashing

### LINKED ISSUE #17: Dockerfile doesn't work
```
➜ docker build -t actuary .
...
➜ docker run actuary 
docker: Error response from daemon: Container command '/go/bin/actuary' not found or does not exist..
```

### PR DESCRIPTION
**Pull request by zuBux**
fixes #17, #18 and #9

### CODE REVIEW

**Comment by zuBux** [comment]
@diogomonica  Should I merge the PR?

**Comment by diogomonica** [comment]
CI failling btw.

File: checks/checks.go [hunk 1]
```diff
@@ -244,23 +244,23 @@ func getFileOwner(info os.FileInfo) (uid, gid string) {
 }
 
 //Helper function to check rules in auditctl
-func checkAuditRule(rule string) bool {
+func checkAuditRule(rule string) (b bool, err error) {
```
Comment (diogomonica) [inline checks/checks.go]: Why does this return a `bool`? Shouldn't it just return an `error`?

File: checks/dockerhost.go [hunk 2]
```diff
@@ -134,9 +134,13 @@ func CheckTrustedUsers(client *client.Client) (res Result) {
...
 	res.Name = "1.7 Audit docker daemon"
-	ruleExists = checkAuditRule("/usr/bin/docker")
+	ruleExists, err := checkAuditRule("/usr/bin/docker")
+	if err != nil {
+		output := fmt.Sprintf("An error occured: %s", err)
+		res.Skip(output)
+		return
+	}
 
 	if ruleExists {
```
Comment (diogomonica) [inline checks/dockerhost.go]: This is not necessary, if we make `checkAuditRule("/usr/bin/docker")` returns an error when the rule doesn't exist.

File: checks/dockerhost.go [hunk 3]
```diff
@@ -162,9 +169,13 @@ func AuditLibDocker(client *client.Client) (res Result) {
 }
 
 func AuditEtcDocker(client *client.Client) (res Result) {
-	var ruleExists bool
 	res.Name = "1.9 Audit Docker files and directories - /etc/docker"
-	ruleExists = checkAuditRule("/etc/docker")
+	ruleExists, err := checkAuditRule("/etc/docker")
+	if err != nil {
```
Comment (diogomonica) [inline checks/dockerhost.go]: Maybe turn the `err` around

``` golang
if err == nil {
  if ruleExists {
     res.Pass()
  } else {
     res.Fail("")
  }
}
return
```

It would be even better if it could be turned into this:

```
if err == nil {
     return res.Pass()
}

return res.Fail(err)
```

**Comment by diogomonica** [comment]
Overall LGTM (CI is failling btw).

I think we should refactor `checkAuditRule` so that each check is smaller.

File: checks/checks.go (hunk 1 above)
Comment (zuBux) [inline checks/checks.go]: The exception is raised when auditd doesn't exist or when the user doesn't have enough privileges to access the rules. The reason that every check has this failing condition is that we can't know which checks will be used in the first place. This causes a check to Skip instead of Fail, since failure would be a false alarm

File: checks/dockerhost.go (hunk 3 above)
Comment (zuBux) [inline checks/dockerhost.go]: Maybe a new error type could solve all of the above problems.

**Comment by zuBux** [comment]
CI is failing because I added some tests that need privileged access to the Docker daemon. On second thought, I might remove them from the repo and only add tests that can be run in a CI.

**Comment by diogomonica** [comment]
@zuBux don't remove them, but apply a tag to them such that they don't run on the CI.

File: checks/dockerhost.go (hunk 3 above)
Comment (diogomonica) [inline checks/dockerhost.go]: Agreed.
